### ISSUE TITLE
gloria protobuf - can we extract coordinates as %.7f please?

### ISSUE THREAD

**Issue by elidana** [GeoNet/delta#137]
Hi @gclitheroe ,

the teqc cfg files for gloria are missing one decimal place in the coordinates, causing a difference in the golden file rinex header for (APPROX POSITION), as noted in https://github.com/GeoNet/gloria/pull/44

Below, the first header content was generated with Delta coordinates (`network/marks.csv`) as input, the second one was generated from coordinates read from the protobuf.
```
testdata/wark210a.17o
- -5115332.9884   477886.9265 -3767147.7746                  APPROX POSITION XYZ
+ -5115333.0047   477886.9640 -3767147.7478                  APPROX POSITION XYZ
```

site coordinates on Delta:
```
[elidana@hutl16534 network]$ grep WARK marks.csv 
WARK,LI,Warkworth,-36.4344143,174.6627794,111.277,NZGD2000,2009-01-01T00:00:00Z,9999-01-01T00:00:00Z
```

site coordinates in the .cfg generated from protobuf
```
elidana@hutl16534 rinex-pkg]$ grep pg WARK201707290000a.cfg
-O.pg -36.434414 174.662779 111.277000
```

can we please change these to be `%.7f` instead of `%.6f` ?
Thanks!!!

(please reassign if that is not for you)

**Comment by ozym** [comment]
@elidana I think you'll find that the protobuf is binary and the issue is the conversion program which doesn't live in this repo.
