### ISSUE TITLE
can we please add "IGS sites" attribute on networks/marks.csv?

### ISSUE THREAD

**Issue by elidana** [GeoNet/delta#140]
We need to identify IGS sites for the Gloria project (see [this issue](https://github.com/GeoNet/gloria/issues/68))

Can we please add a tag or something that is in addition to the network code ?
The "best" place IMO would be https://github.com/GeoNet/delta/blob/master/network/marks.csv

Not sure who to assign that to and how this is impacted by the sync with Oracle database.

**Comment by ozym** [comment]
There's a network called IG in the networks file, maybe setting the network codes in the marks file is all  that's needed (the network code was used more for internal use - dots on maps or ownership information).

The only thing (apart from dots on maps etc) I can see the network code being used for is to assign some form of attribution for the data source.

**Comment by ozym** [comment]
Resolved via #141
