### ISSUE TITLE
GeodesyML schema

### ISSUE THREAD

**Issue by elidana** [GeoNet/delta#2]
The IGS Data Center working group is working on a new XML schema for GNSS(/GPS) metadata exchange. 
The schema will be based on what is called GeodesyML schema, defined by an australia and new zealand working group. 
More info here:
http://icsm.govspace.gov.au/egeodesy/geodesyml-0-2-schema/

this is likely to be very similar to the future IGS standard, and LINZ will want to adopt that one for the PositioNZ stations.

Below a link to a presentation we assisted at the last IGS workshop in sydney, that give the current status of the project:
http://acc.igs.org/workshop2016/presentations/Plenary_07_05.pdf

I think is good to keep that in mind for _future_ delta-ng developments

**Comment by ozym** [comment]
https://github.com/GeoscienceAustralia/GeodesyML

**Comment by ozym** [comment]
we can come back to this if required
