### ISSUE TITLE
SENSOR suffix on Type

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/delta#59]
Once we're done with Oracle there could be some simplification on sensor type keys in `resp/auto/SensorModels` 

The check for variable suffix in `stations_test.go` should not be needed:

```
for _, v := range recorders {
		st, ok := resp.SensorModels[v.InstalledSensor.Model]
		if !ok {
			// in resp/auto.go some models have " SENSOR" appended.
			st, ok = resp.SensorModels[v.InstalledSensor.Model + " SENSOR"]
		}
```

**Comment by ozym** [comment]
no longer required due to tech pivot
